Enable fmt and clippy, disable codecov upload on CI

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -30,19 +30,14 @@ jobs:
         uses: mozilla-actions/sccache-action@v0.0.3
         with:
           version: "v0.4.0"
-      - name: Run cargo check
-        run: cargo check
-# Disabled Due to issue with rustfmt our team has.
-#      - name: Run cargo fmt check
-#        run: |
-#          set;
-#          ls -la ~/.config/;
-#          cargo --version;
-#          cargo fmt --version;
-#          if ! cargo fmt --check --verbose ; then
-#            echo "Formatting errors detected, please run 'cargo fmt' to fix it";
-#            exit 1
-#          fi
+      - name: Run cargo clippy
+        run: cargo clippy --all-features --all-targets -- -D warnings
+      - name: Run cargo fmt check
+        run: |
+          if ! cargo fmt --check --verbose ; then
+            echo "Formatting errors detected, please run 'cargo fmt' to fix it";
+            exit 1
+          fi
 
   # Check that every combination of features is working properly.
   hack:
@@ -86,7 +81,7 @@ jobs:
         with:
           version: "v0.4.0"
       - name: Run cargo test
-        run: cargo test
+        run: cargo test --all-features
   coverage:
     runs-on: ubuntu-latest
     env:
@@ -112,7 +107,3 @@ jobs:
         run: cargo generate-lockfile
       - name: cargo llvm-cov
         run: cargo llvm-cov --locked --all-features --lcov --output-path lcov.info
-      - name: Upload to codecov.io
-        uses: codecov/codecov-action@v3
-        with:
-          fail_ci_if_error: true
